#!/usr/bin/env python3
"""Regenerate the "Blueprint render" preview in docs/index.html.

The preview must always reflect what `arazzo-maestro view` actually
produces, so it is *generated*, never hand-written. This script:

  1. Renders the demo workflow with the real binary, once per built-in
     theme (light, dark). It prefers `go run ./cmd/arazzo-maestro` so the
     output is current; if the Go toolchain is unavailable it falls back
     to the committed dist/<theme>/<workflow>.html (also real `view`
     output) so the page can still be regenerated in constrained envs.
  2. Adapts each page for safe, request-free embedding:
       - strips the Tailwind CDN <script> (keeps the page at 0 network
         requests, eco-design R1; the layout patch below replaces the
         few Tailwind utility classes the template relies on),
       - works around a known renderer bug where `--font-primary` is
         emitted as `ZgotmplZ` (theme.FontStack returns a string that
         html/template neutralises in a CSS context; fix = return
         template.CSS). This line becomes a no-op once that is fixed.
  3. Inlines each adapted page into an <iframe srcdoc>, iframes give
     perfect CSS isolation, so the embedded render is byte-faithful to
     `view` with no risk of the landing page's own styles leaking in.
  4. Writes the two iframes into docs/index.html between the
     PREVIEW:BEGIN / PREVIEW:END markers.

Usage:  python3 docs/gen-preview.py
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
INDEX = REPO / "docs" / "index.html"
WORKFLOW_FILE = "examples/shop.arazzo.yaml"
# dist/ is organised per example: dist/<example>/<theme>/<workflow>.html
EXAMPLE = Path(WORKFLOW_FILE).name.split(".")[0]
WORKFLOW_ID = "happy-path-checkout"
THEMES = ("light", "dark")
# The landscape variant is shown once, full-width, under the two portrait
# theme specimens. Light reads best against the landing's own surface.
LANDSCAPE_THEME = "light"

BEGIN = "<!-- PREVIEW:BEGIN (generated by docs/gen-preview.py, do not edit by hand) -->"
END = "<!-- PREVIEW:END -->"

# Matches theme.FontStack("sans"); both built-in themes use font: sans.
SANS_STACK = (
    'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, '
    '"Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif'
)

# Replaces the Tailwind utility classes the template puts on <body>/<main>
# so the render stays well laid out once the CDN script is removed.
LAYOUT_PATCH = (
    "\n    /* preview embedding patch (gen-preview.py) */\n"
    "    body { margin: 0; min-height: 0; }\n"
    "    main { max-width: 46rem; margin: 0 auto; padding: 1.25rem 1.5rem; }\n"
)


def render_with_go(theme: str, out_dir: Path, layout: str = "portrait") -> Path | None:
    """Render via the real binary. Returns the file path, or None if Go
    is unavailable / the command fails."""
    if shutil.which("go") is None:
        return None
    cmd = [
        "go", "run", "./cmd/arazzo-maestro", "view", WORKFLOW_FILE,
        "--workflow", WORKFLOW_ID, "--theme", theme, "--layout", layout,
        "-o", str(out_dir),
    ]
    try:
        subprocess.run(cmd, cwd=REPO, check=True,
                       stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except (subprocess.CalledProcessError, OSError) as exc:
        print(f"  go run failed for {theme}/{layout}: {exc}", file=sys.stderr)
        return None
    path = out_dir / f"{WORKFLOW_ID}.html"
    return path if path.exists() else None


def source_html(theme: str, tmp: Path, layout: str = "portrait") -> tuple[str, str]:
    """Return (html, origin) for a theme/layout, preferring fresh `go run`."""
    # Portrait keeps the historical dist/<example>/<theme>/ path; landscape
    # gets a sibling suffix so a fallback never overwrites the portrait one.
    variant = theme if layout == "portrait" else f"{theme}-{layout}"
    out_dir = tmp / variant
    out_dir.mkdir(parents=True, exist_ok=True)
    rendered = render_with_go(theme, out_dir, layout)
    if rendered is not None:
        return rendered.read_text(encoding="utf-8"), "go run (fresh)"
    fallback = REPO / "dist" / EXAMPLE / variant / f"{WORKFLOW_ID}.html"
    if not fallback.exists():
        sys.exit(f"ERROR: no source for '{variant}': Go unavailable and "
                 f"{fallback} is missing. Run `arazzo-maestro view "
                 f"{WORKFLOW_FILE} -o dist/{EXAMPLE}/{variant} --theme {theme} "
                 f"--layout {layout}` first.")
    return fallback.read_text(encoding="utf-8"), "dist/ (fallback)"


def adapt(html: str) -> str:
    """Make a standalone `view` page safe to embed request-free."""
    out_lines = []
    for line in html.splitlines():
        if "cdn.tailwindcss.com" in line:
            continue  # eco-design R1: keep the landing at 0 requests
        if "--font-primary:" in line and "ZgotmplZ" in line:
            indent = line[: len(line) - len(line.lstrip())]
            out_lines.append(f"{indent}--font-primary: {SANS_STACK};")
            continue
        out_lines.append(line)
    adapted = "\n".join(out_lines)
    # Inject the layout patch just before the closing </style>.
    adapted = adapted.replace("</style>", LAYOUT_PATCH + "  </style>", 1)
    return adapted


def to_srcdoc(html: str) -> str:
    """Escape an HTML document for a double-quoted srcdoc attribute."""
    return html.replace("&", "&amp;").replace('"', "&quot;")


def build_block(previews: list[tuple[str, str]], landscape_html: str) -> str:
    """previews: list of (theme, adapted_html) shown as the two portrait
    specimens; landscape_html: the full-width landscape variant below them."""
    parts = ['        <div class="specimens">']
    for theme, html in previews:
        srcdoc = to_srcdoc(html)
        title = f"{WORKFLOW_ID} rendered with the {theme} theme"
        parts.append(f'''          <div class="spec-wrap">
            <p class="spec-label">Theme: {theme}, live `view` output</p>
            <iframe class="preview-frame" title="{title}" loading="lazy" sandbox srcdoc="{srcdoc}"></iframe>
          </div>''')
    parts.append("        </div>")

    srcdoc = to_srcdoc(landscape_html)
    title = f"{WORKFLOW_ID} rendered in landscape layout"
    parts.append(f'''        <div class="spec-wrap spec-wide">
          <p class="spec-label">Layout: landscape (--layout landscape), scrolls sideways, live `view` output</p>
          <iframe class="preview-frame preview-frame-wide" title="{title}" loading="lazy" sandbox srcdoc="{srcdoc}"></iframe>
        </div>''')
    return "\n".join(parts)


def main() -> None:
    if not INDEX.exists():
        sys.exit(f"ERROR: {INDEX} not found.")
    index_html = INDEX.read_text(encoding="utf-8")
    if BEGIN not in index_html or END not in index_html:
        sys.exit("ERROR: PREVIEW:BEGIN/END markers not found in index.html.")

    previews = []
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        for theme in THEMES:
            html, origin = source_html(theme, tmp)
            print(f"  {theme:5s} portrait : {origin}")
            previews.append((theme, adapt(html)))
        land_html, origin = source_html(LANDSCAPE_THEME, tmp, "landscape")
        print(f"  {LANDSCAPE_THEME:5s} landscape: {origin}")
        landscape = adapt(land_html)

    block = build_block(previews, landscape)
    pre = index_html.split(BEGIN)[0]
    post = index_html.split(END)[1]
    new_html = f"{pre}{BEGIN}\n{block}\n        {END}{post}"
    INDEX.write_text(new_html, encoding="utf-8")
    print(f"Updated {INDEX.relative_to(REPO)} ({len(new_html)} bytes).")


if __name__ == "__main__":
    main()
